# Generated by Django 4.0.5 on 2022-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_bookrental_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrental',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
